# Generated by Django 4.0.6 on 2024-11-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalizado',
            name='bloqueada',
            field=models.BooleanField(default=False),
        ),
    ]
