# Generated by Django 5.1.3 on 2024-12-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userpersonalizado_bloqueada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalizado',
            name='imagen',
            field=models.ImageField(default='perfil-default.png', upload_to=''),
        ),
    ]
