"""
Django settings for eesn3_proyecto project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*^d69dtuf&@)i3c1q!+s*-kn14n5@s83w@k-v1h)z@jq-0e7xd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["EESN3Jeppener.pythonanywhere.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'murosocial.apps.MurosocialConfig',
    'login.apps.LoginConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eesn3_proyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eesn3_proyecto.wsgi.application'

#Conexión al servicio de correo
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Usamos SMTP

#Conexión al servicio de correo con Gmail
EMAIL_HOST = 'smtp.gmail.com'  # Servidor SMTP de Gmail
EMAIL_PORT = 587  # Puerto para la conexión TLS

#Medida de seguridad
EMAIL_USE_TLS = True  # Usar TLS para la conexión segura

#Configuración del correo
EMAIL_HOST_USER = 'juancampotc1@gmail.com'  # Mi dirección de correo de Gmail
EMAIL_HOST_PASSWORD = 'bniu rhbq zaaq zqbn'  #Mi contraseña de Gmail para aplicaciones
DEFAULT_FROM_EMAIL = 'juancampotc1@gmail.com'  # Dirección de correo desde la cual se enviarán los correos


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': 'EESN3Jeppener.mysql.pythonanywhere-services.com',
        'USER': 'EESN3Jeppener',
        'PASSWORD': 'basededatos123',
        'NAME': 'EESN3Jeppener$default',
        'CHARSET': 'utf8',
        'OPTIONS':{
            'sql_mode': "STRICT_ALL_TABLES",
            }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
######  AGREGADO  ######


#STATIC_URL, será la carpeta donde se almacenarán todos las carpetas y archivos estáticos
STATIC_URL = 'static/'
#STATIC_ROOT, será la ubicación de la carpeta "static", la cual como se le indica estará en la raiz del proyecto
STATIC_ROOT = os.path.join(BASE_DIR, "allstatics")
# Y te ahorras de tener que escribir toda la ruta absoluta perri (2/11/24)
"""
STATIC_ROOT = '/home/EESN3Jeppener/eesn3_proyecto/allstatics'
"""

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# VARIABLES DE REDIRRECIÓN DE LOGIN Y LOGOUT (2/11/24)
LOGIN_REDIRECT_URL = "inicio"
LOGOUT_REDIRECT = "inicio" # agrege ésta variable (2/11/24)#
#con esto ahora serás redirigido a la página de inicio cada vez que inicies o cierres sesión


# MEDIA_URL, será la carpeta donde se almacenarán los archivos de los usuarios
MEDIA_URL = "media/"

# MEDIA_ROOT, será la ubicación de la carpeta "media", la cual estará en la raíz de la carpeta del proyecto
MEDIA_ROOT = os.path.join(BASE_DIR, "media")



# Ahora que creamos otro modelo de manejo de usuarios, le especificamos a
# Django que vamos a usar éste modelo para el manejo de usuarios y login,
# el cual se encuentra en la app llamada applogin.
AUTH_USER_MODEL = "login.UserPersonalizado"