# Generated by Django 5.1.3 on 2024-12-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murosocial', '0004_alter_imagen_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='nom_usuario',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
