# Generated by Django 5.1.3 on 2024-12-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murosocial', '0005_imagen_nom_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='nom_usuario',
        ),
        migrations.AddField(
            model_name='imagen',
            name='url_absoluta',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
